apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
        - name: vprodb
          image: vprofile/vprofiledb:V1
          args:
            # we use this arg to ignore the lost+found directory and map our volume to /var/lib/mysql
            - "--ignore-db-dir"
            - "lost+found"
            - "ignore-db-dir=lost+found"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: vpro-db-data
          ports:
             - name: vprodb-port
               containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-pass
      nodeSelector:
        zone: eu-west-2a
      volumes:
        - name: vpro-db-data
          awsElasticBlockStore:
            volumeID: vol-06820a06eb49f8cbb
            fsType: ext4
